pub mod common;

pub mod animate;
pub mod batch;
pub mod blur;
pub mod brightness;
pub mod contrast;
pub mod convert;
pub mod crop;
pub mod diff;
pub mod draw;
pub mod edge_detect;
pub mod emboss;
pub mod flip;
pub mod frames;
pub mod gif_speed;
pub mod grayscale;
pub mod hue_rotate;
pub mod info;
pub mod invert;
pub mod orient;
pub mod overlay;
#[cfg(feature = "pdf")]
pub mod pdf_pages;
pub mod pipeline;
pub mod posterize;
#[cfg(feature = "psd")]
pub mod psd_info;
#[cfg(feature = "psd")]
pub mod psd_layers;
pub mod resize;
pub mod rotate;
pub mod saturate;
pub mod sepia;
pub mod set_density;
pub mod sharpen;
pub mod smart_crop;
#[cfg(feature = "text")]
pub mod text;
pub mod tilt_shift;
pub mod tint;
#[cfg(feature = "tiny")]
pub mod tiny;
pub mod trim;

pub type CommandResult = std::result::Result<i32, panimg_core::error::PanimgError>;
